import { ProductConfig } from "@/type";

export const footerConfig = {
  logo: "/logo/logo-left-title.png",
  company: "加纳YUHE公司",
  establishedYear: "2017",
  officeLocation: "北部城市Tamale",
  description:
    "加纳YUHE公司成立于2017年，办公室位于北部城市Tamale。是一家从事工程建筑、工程机械进口、农业机械进口、网站建设以及国际货物运输的集团公司。本公司重视客户是上帝的经营理念，以诚信为基本服务准则。通过全面的产品库和强大的开发能力，为客户提供价格低廉、品质上乘的相关产品和运输服务。有任何需求请联系我们，我们一定会提供优质的服务。",
  socialLinks: [
    {
      icon: "/social-link/whatsapp.svg",
      href: "https://wa.me/233540125194",
    },
    {
      icon: "/social-link/gmail.png",
      href: "#", // Replace with the actual email link
    },
  ],
  quickLinks: [
    { title: "首页", href: "#" },
    { title: "网站地图", href: "#" },
    { title: "关于我们", href: "#" },
    { title: "业务范围", href: "#" },
    { title: "联系我们", href: "#" },
  ],
  supports: [
    { title: "Setting & Privacy", href: "#" },
    { title: "Help & Support", href: "#" },
    { title: "Terms & Conditions", href: "#" },
    { title: "24/7 Supports", href: "#" },
    { title: "On Point FAQ", href: "#" },
  ],
  // copyrightText: "© Yuhe - All Rights Reserved",
  copyrightText: "© 2019-2024 Yuhe - All Rights Reserved, Powered by Yuhe",
  footerShape1: "/static/footer-shape-1.svg",
  footerShape2: "/static/footer-shape-2.svg",
};

export const headerConfig = {
  logo: "/logo/logo-left-title.png",
  links: [
    { label: "首页", href: "/" },
    { label: "工程机械", href: "/engineering" },
    { label: "农业机械", href: "/agricultural" },
    { label: "运输业务", href: "/transportation" },
    // {
    //   label: "其他业务",
    //   href: "#",
    //   subItems: [
    //     { label: "发展战略", href: "/blog-grid" },
    //     { label: "全球业务", href: "/token-sale" },
    //     { label: "Support Page", href: "/support" },
    //     { label: "Signin Page", href: "/signin" },
    //     { label: "Signup Page", href: "/signup" },
    //   ],
    // },
    { label: "关于我们", href: "/about" },
  ],
};

export const productsConfig: ProductConfig[] = [
  {
    type: "engineering",
    title: "工程机械",
    products: [
      {
        name: "临工L955H",
        type: "loader",
        typeName: "装载机",
        desc: "山东临工L955H装载机：动力强劲，节能环保，操作便捷，维护简便，适合多种作业环境。",
        smallImg: "/images/products/engineer/loaders/临工L955H/1.jpg",
        images:
          "/images/products/engineer/loaders/临工L955H/1.jpg,/images/products/engineer/loaders/临工L955H/2.jpg,/images/products/engineer/loaders/临工L955H/3.jpg,/images/products/engineer/loaders/临工L955H/4.jpg",
        features: "1. 动力强劲, 2. 节能环保, 3. 操作简便, 4. 维护方便",
        parameter: " ",
      },
      {
        name: "柳工CLG870H",
        type: "loader",
        typeName: "装载机",
        desc: "柳工CLG870H装载机具备高效、舒适、节能、易维护等优势。",
        smallImg: "/images/products/engineer/loaders/柳工CLG870H/图片1.jpg",
        images: "",
        features: "1. 动力强劲 2. 作业高效 3. 操控灵活 4. 节能环保",
        parameter: "",
      },
      {
        name: "龙工LG855N",
        type: "loader",
        typeName: "装载机",
        desc: "龙工LG855H装载机动力强劲，操控简便，效率高，经济实用。",
        smallImg: "/images/products/engineer/loaders/龙工LG855N/图片1.jpg",
        images: "",
        features: "1. 动力性能强 2. 操控全液压 3. 起升力大 4. 经济耐用",
        parameter: "",
      },
      {
        name: "厦工XG958K",
        type: "loader",
        typeName: "装载机",
        desc: "厦工XG958K装载机以高承载、高效、节能、易操控著称。",
        smallImg: "/images/products/engineer/loaders/厦工XG958K/图片1.jpg",
        images: "",
        features: "1. 承载力强 2. 工作效率高 3. 燃油经济 4. 操控灵活",
        parameter: "",
      },
      {
        name: "罐车",
        type: "truck",
        typeName: "罐车",
        desc: "外观整洁，内部清洁，适合运输各种液体货物。其密封性能良好，确保运输过程中的安全无泄漏。",
        smallImg: "/images/products/engineer/truck/1.jpg",
        images: "",
        features: "1. 外观整洁 2. 内部清洁 3. 密封性能好 4. 适合液体运输",
        parameter: "",
      },
      {
        name: "罐车",
        type: "truck",
        typeName: "罐车",
        desc: "油罐车专为安全高效运输液体燃料设计。",
        smallImg: "/images/products/engineer/truck/4.jpg",
        images: "",
        features: "1. 安全运输 2. 高效装卸 3. 防爆设计 4. 易于维护",
        parameter: "",
      },
      {
        name: "精品二手 01",
        type: "usedcar",
        typeName: "二手车",
        desc: "这款二手履带式挖掘机外观保养良好，性能稳定，适合中小型土方工程。其耐用的履带设计保证了在各种地形上的稳定作业",
        smallImg: "/images/products/engineer/usedcar/01/usedcar11.jpg",
        images: "",
        features: "1. 外观保养佳 2. 性能稳定 3. 履带耐用 4. 适合中小型工程",
        parameter: "",
      },
      {
        name: " 精品二手 02",
        type: "usedcar",
        typeName: "二手车",
        desc: "此款二手履带式挖掘机成色较新，操作简便，动力强劲，适合进行重型挖掘作业。其高效的液压系统提供了出色的挖掘力。",
        smallImg: "/images/products/engineer/usedcar/02/usedcar21.jpg",
        images: "",
        features: "1. 成色较新 2. 操作简便 3. 动力强劲 4. 高效液压系统",
        parameter: "",
      },
      {
        name: " 精品二手 03",
        type: "usedcar",
        typeName: "二手车",
        desc: "这款二手履带式挖掘机经过专业维护，性能可靠，具备良好的燃油经济性，适合长时间连续作业。其坚固的结构设计保证了耐用性。",
        smallImg: "/images/products/engineer/usedcar/03/usedcar31.jpg",
        images: "",
        features: "1. 专业维护 2. 性能可靠 3. 燃油经济 4. 结构坚固",
        parameter: "",
      },
      {
        name: " 精品二手 04",
        type: "usedcar",
        typeName: "二手车",
        desc: "这款二手履带式挖掘机虽然外观略显磨损，但内部机械状况良好，性价比高，适合预算有限但需要可靠挖掘力的用户。",
        smallImg: "/images/products/engineer/usedcar/04/usedcar41.jpg",
        images: "",
        features: "1. 性价比高 2. 内部状况良好 3. 适合预算有限 4. 可靠挖掘力",
        parameter: "",
      },
      {
        name: "小松PC200-11M0",
        type: "excavator",
        typeName: "挖掘机",
        desc: "小松PC200-11M0挖掘机以其卓越的性能、可靠性、燃油经济性和智能化控制系统在挖掘作业中表现出色。",
        smallImg:
          "/images/products/engineer/excavators/小松PC200-11M0/图片1.jpg",
        images: "",
        features: "1. 性能出色 2. 动力强劲 3. 操作灵活 4. 人性化设计",
        parameter: "",
      },
      {
        name: "SANY 215C",
        type: "excavator",
        typeName: "挖掘机",
        desc: "SY215C挖掘机凭借其强大的动力、精准操控、高效工作能力、舒适操作环境、高度可靠性、环保节能和维护方便性，成为理想的工程设备。",
        smallImg: "/images/products/engineer/excavators/SANY 215C/图片1.jpg",
        images: "",
        features: "1. 动力强劲 2. 操控精准 3. 高效作业 4. 舒适驾驶室",
        parameter: "",
      },
      {
        name: "SANY 215H",
        type: "excavator",
        typeName: "挖掘机",
        desc: "三一重工SY215H挖掘机以其卓越的动力、高效作业、燃油经济性、简便操作、舒适性、高可靠性和维修便捷性，满足多样化工程需求。",
        smallImg: "/images/products/engineer/excavators/SANY 215H/图片1.jpg",
        images: "",
        features: "1. 动力强劲 2. 作业高效 3. 燃油经济 4. 操作简便",
        parameter: "",
      },
      {
        name: "SANY 335H",
        type: "excavator",
        typeName: "挖掘机",
        desc: "三一重工SY335H挖掘机以其卓越的挖掘力、高效智能作业、舒适驾驶体验、稳定性和易维护性成为工程机械设备的理想选择。",
        smallImg: "/images/products/engineer/excavators/SANY 335H/图片1.jpg",
        images: "",
        features: "1. 挖掘能力强 2. 作业效率高 3. 驾驶室舒适 4. 维护便捷",
        parameter: "",
      },
    ],
  },
  {
    type: "agricultural",
    title: "农业机械",
    products: [
      {
        name: "AF88",
        type: "tractor",
        typeName: "收割机",
        desc: "AF88履带式联合收割机是高效、高配置、高品质的纵轴流收割机型，适合全喂入水稻收割。",
        smallImg: "/images/products/agricultural/水稻收割机/AF88.jpg",
        images: "",
        features: "1. 高效收割 2. 高端配置 3. 纵轴流设计 4. 适合水稻",
        parameter: "",
      },
      {
        name: "RG108",
        type: "tractor",
        typeName: "收割机",
        desc: "RG108PLUS履带式联合收割机专为高产量水稻设计，底盘升级，确保高效率收割。",
        smallImg: "/images/products/agricultural/水稻收割机/RG108.jpg",
        images: "",
        features: "1. 高产量设计 2. 底盘升级 3. 收获效率高 4. 适合水稻",
        parameter: "",
      },
      {
        name: "瑞得RD900",
        type: "truck",
        typeName: "拖拉机",
        desc: "瑞得RD900拖拉机配备东方红发动机，具有大扭矩、低油耗、高可靠性，适合牵引和驱动作业，结构紧凑，操作灵活。",
        smallImg: "/images/products/agricultural/拖拉机/900.jpg",
        images: "",
        features: "1. 东方红发动机 2. 动力强劲 3. 结构紧凑 4. 操作灵活",
        parameter: "",
      },
      {
        name: "瑞得RD904",
        type: "truck",
        typeName: "拖拉机",
        desc: "瑞得RD904拖拉机，东方红发动机，动力强劲，油耗低，结构紧凑，操作灵活。",
        smallImg: "/images/products/agricultural/拖拉机/904.jpg",
        images: "",
        features: "1. 扭矩大动力强 2. 高可靠性 3. 结构紧凑 4. 液压转向",
        parameter: "",
      },
      {
        name: "瑞得RD1000",
        type: "truck",
        typeName: "拖拉机",
        desc: "瑞得RD1000轮式拖拉机，搭载东方红发动机，提供强大动力，结构紧凑，操作灵活。",
        smallImg: "/images/products/agricultural/拖拉机/1000.jpg",
        images: "",
        features: "1. 扭矩大动力强 2. 低油耗高可靠性 3. 结构紧凑 4. 液压转向",
        parameter: "",
      },
    ],
  },
];

export const transportationConfig = {
  overview:
    "裕禾船务专注于提供高效、经济的国际物流解决方案，服务网络遍布全球，包括非洲、欧洲、地中海、南美、北美、中东、东南亚等地区。我们与全球90%以上的知名集装箱班轮公司建立了长期合作关系，并通过自主研发的运价平台，为客户提供全面的航线选择、船期信息和个性化的物流服务。我们的服务不仅限于海运，还涵盖了空运、多式联运、特种货物运输、散杂货运输、仓储配送以及清关报检等全方位物流服务，满足客户多样化的运输需求。",
  services: [
    {
      name: "集装箱运输及多式联运",
      desc: "裕禾船务提供全球范围内的集装箱运输服务，业务区域覆盖非洲、欧洲、地中海等主要港口。我们与多家国际班轮公司合作，确保客户享有优惠的运价和灵活的船期选择。此外，我们的多式联运服务结合海运、铁路、公路和航空等多种运输方式，为客户提供定制化的物流解决方案，满足特殊运输需求。",
      src: "/images/transportation/01.png",
    },
    {
      name: "特种货物及危险品运输",
      desc: "针对超大、超重机械、危险品和化工品、冷藏货物等特种货物，裕禾船务提供专业的运输服务。我们拥有丰富的操作经验和专业的运输设备，确保货物安全、高效地到达目的地。无论是大型建设项目还是危险品运输，我们都能提供量身定制的物流方案。",
      src: "/images/transportation/01.png",
    },
    {
      name: "散杂货运输及项目物流",
      desc: "裕禾船务为原材料、大宗商品、大型项目建设等提供散杂货运输服务。我们与散杂船船东和合作伙伴建立了紧密的合作关系，确保为客户提供快速、可靠的运输方案。无论是散装货物还是特殊项目物流，我们都能提供专业的服务和支持。",
      src: "/images/transportation/01.png",
    },
    {
      name: "国际航空运输代理",
      desc: "裕禾船务的国际航空运输代理服务专注于“小而精且急”的货物运输需求。我们与各大航空公司合作，提供快速、可靠的空运服务。我们的服务宗旨是“专业受托，快速反应，使命必达”，确保客户的货物能够安全、及时地到达目的地。",
      src: "/images/transportation/01.png",
    },
    {
      name: "仓储及拆装箱物流配送",
      desc: "裕禾船务提供全面的仓储和物流配送服务，包括集装箱货物、散杂货物、大件货物的仓储、内装箱、拆箱、分拨和中转。我们的仓库供应商地理位置优越，服务专业，能够满足不同货物类别的存储和操作需求。同时，我们的物流车队供应商提供卫星定位服务，确保货物运输的安全性和及时性。",
      src: "/images/transportation/01.png",
    },
    {
      name: "代理清关报检及代办国际运输保险",
      desc: "裕禾船务为客户提供一站式的清关、报检和保险服务。我们的清关服务覆盖全球主要口岸，由可靠的当地代理负责安排。报检业务专注于中国大陆的进出口商检、食品和卫生检验检疫。我们的保险服务快速出单，费率优惠，为客户提供全面的货物运输保障。",
      src: "/images/transportation/01.png",
    },
  ],
};
