export const footerConfig = {
  logo: "/logo/logo-left-title.png",
  company: "加纳YUHE公司",
  establishedYear: "2017",
  officeLocation: "北部城市Tamale",
  description:
    "加纳YUHE公司成立于2017年，办公室位于北部城市Tamale。是一家从事工程建筑、工程机械进口、农业机械进口、网站建设以及国际货物运输的集团公司。本公司重视客户是上帝的经营理念，以诚信为基本服务准则。通过全面的产品库和强大的开发能力，为客户提供价格低廉、品质上乘的相关产品和运输服务。有任何需求请联系我们，我们一定会提供优质的服务。",
  socialLinks: [
    {
      icon: "/social-link/whatsapp.svg",
      href: "https://wa.me/233540125194",
    },
    {
      icon: "/social-link/gmail.png",
      href: "#", // Replace with the actual email link
    },
  ],
  quickLinks: [
    { title: "首页", href: "#" },
    { title: "网站地图", href: "#" },
    { title: "关于我们", href: "#" },
    { title: "业务范围", href: "#" },
    { title: "联系我们", href: "#" },
  ],
  supports: [
    { title: "Setting & Privacy", href: "#" },
    { title: "Help & Support", href: "#" },
    { title: "Terms & Conditions", href: "#" },
    { title: "24/7 Supports", href: "#" },
    { title: "On Point FAQ", href: "#" },
  ],
  copyrightText:
    "© Crypto - All Rights Reserved, Crafted by Next.js Templates",
  footerShape1: "/static/footer-shape-1.svg",
  footerShape2: "/static/footer-shape-2.svg",
};

export const headerConfig = {
  logo: "/logo/logo-left-title.png",
  links: [
    { label: "首页", href: "/" },
    { label: "工程机械", href: "/engineering" },
    { label: "农业机械", href: "/agricultural" },
    { label: "运输业务", href: "/transportation" },
    // {
    //   label: "其他业务",
    //   href: "#",
    //   subItems: [
    //     { label: "发展战略", href: "/blog-grid" },
    //     { label: "全球业务", href: "/token-sale" },
    //     { label: "Support Page", href: "/support" },
    //     { label: "Signin Page", href: "/signin" },
    //     { label: "Signup Page", href: "/signup" },
    //   ],
    // },
    { label: "关于我们", href: "/about" },
  ],
};

export const productsConfig = [
  {
    type: "engineering",
    title: "工程机械",
    products: [
      {
        name: "临工L955H",
        type: "loader",
        typeName: "装载机",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "柳工CLG870H",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "龙工LG855N",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "厦工XG958K",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "罐车",
        type: "truck",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "罐车",
        type: "truck",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "精品二手 01",
        type: "usedcar",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: " 精品二手 02",
        type: "usedcar",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: " 精品二手 03",
        type: "usedcar",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: " 精品二手 04",
        type: "usedcar",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "小松PC200-11M0",
        type: "excavator",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "SANY 215C",
        type: "excavator",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "SANY 215H",
        type: "excavator",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "SANY 335H",
        type: "excavator",
        desc: "临工L955H是一款高性能的工业机器人，具有高精度、高速度、高精密、高可靠性、高可靠性、高可",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
    ],
  },
  {
    type: "agricultural",
    title: "农业机械",
    products: [
      {
        name: "AF88",
        type: "tractor",
        desc: "AF系列全喂入水稻机是经过多年技术升级和市场验证精心打造的高端纵轴流机型，具有高配置、高效率、高品质的特点，是同类机型的替代产品。",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "RG108",
        type: "tractor",
        desc: "AF系列全喂入水稻机是经过多年技术升级和市场验证精心打造的高端纵轴流机型，具有高配置、高效率、高品质的特点，是同类机型的替代产品。",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "AF88",
        type: "tractor",
        desc: "AF系列全喂入水稻机是经过多年技术升级和市场验证精心打造的高端纵轴流机型，具有高配置、高效率、高品质的特点，是同类机型的替代产品。",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "RG800",
        type: "truck",
        desc: "瑞得RD1804拖拉机",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "RM1804",
        type: "truck",
        desc: "瑞得RD1804拖拉机",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "RM1804",
        type: "truck",
        desc: "瑞得RD1804拖拉机",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
      {
        name: "RA1300",
        type: "truck",
        desc: "瑞得RD1804拖拉机",
        smallImg: "",
        images: "",
        features: "",
        parameter: "",
      },
    ],
  },
];
