import { Product, ProductConfig } from "@/type";

export const footerConfig = {
  logo: "/logo/logo-left-title.png",
  company: "加纳YUHE公司",
  establishedYear: "2017",
  officeLocation: "北部城市Tamale",
  description:
    "加纳YUHE公司成立于2017年，办公室位于北部城市Tamale。是一家从事工程建筑、工程机械进口、农业机械进口、网站建设以及国际货物运输的集团公司。本公司重视客户是上帝的经营理念，以诚信为基本服务准则。通过全面的产品库和强大的开发能力，为客户提供价格低廉、品质上乘的相关产品和运输服务。有任何需求请联系我们，我们一定会提供优质的服务。",
  socialLinks: [
    {
      icon: "/social-link/whatsapp.svg",
      href: "https://wa.me/233540125194",
    },
    {
      icon: "/social-link/gmail.png",
      href: "#", // Replace with the actual email link
    },
  ],
  quickLinks: [
    { title: "首页", href: "#" },
    { title: "网站地图", href: "#" },
    { title: "关于我们", href: "#" },
    { title: "业务范围", href: "#" },
    { title: "联系我们", href: "#" },
  ],
  supports: [
    { title: "Setting & Privacy", href: "#" },
    { title: "Help & Support", href: "#" },
    { title: "Terms & Conditions", href: "#" },
    { title: "24/7 Supports", href: "#" },
    { title: "On Point FAQ", href: "#" },
  ],
  copyrightText:
    "© Crypto - All Rights Reserved, Crafted by Next.js Templates",
  footerShape1: "/static/footer-shape-1.svg",
  footerShape2: "/static/footer-shape-2.svg",
};

export const headerConfig = {
  logo: "/logo/logo-left-title.png",
  links: [
    { label: "首页", href: "/" },
    { label: "工程机械", href: "/engineering" },
    { label: "农业机械", href: "/agricultural" },
    { label: "运输业务", href: "/transportation" },
    // {
    //   label: "其他业务",
    //   href: "#",
    //   subItems: [
    //     { label: "发展战略", href: "/blog-grid" },
    //     { label: "全球业务", href: "/token-sale" },
    //     { label: "Support Page", href: "/support" },
    //     { label: "Signin Page", href: "/signin" },
    //     { label: "Signup Page", href: "/signup" },
    //   ],
    // },
    { label: "关于我们", href: "/about" },
  ],
};

export const productsConfig: ProductConfig[] = [
  {
    type: "engineering",
    title: "工程机械",
    products: [
      {
        name: "临工L955H",
        type: "loader",
        typeName: "装载机",
        desc: "山东临工L955H装载机：动力强劲，节能环保，操作便捷，维护简便，适合多种作业环境。",
        smallImg: "/images/products/engineer/loaders/临工L955H/1.jpg",
        images:
          "/images/products/engineer/loaders/临工L955H/1.jpg,/images/products/engineer/loaders/临工L955H/2.jpg,/images/products/engineer/loaders/临工L955H/3.jpg,/images/products/engineer/loaders/临工L955H/4.jpg",
        features: "1. 动力强劲, 2. 节能环保, 3. 操作简便, 4. 维护方便",
        parameter: " ",
      },
      {
        name: "柳工CLG870H",
        type: "loader",
        typeName: "装载机",
        desc: "柳工CLG870H装载机具备高效、舒适、节能、易维护等优势。",
        smallImg: "/images/products/engineer/loaders/柳工CLG870H/图片1.jpg",
        images: "",
        features: "1. 动力强劲 2. 作业高效 3. 操控灵活 4. 节能环保",
        parameter: "",
      },
      {
        name: "龙工LG855N",
        type: "loader",
        typeName: "装载机",
        desc: "龙工LG855H装载机动力强劲，操控简便，效率高，经济实用。",
        smallImg: "/images/products/engineer/loaders/龙工LG855N/图片1.jpg",
        images: "",
        features: "1. 动力性能强 2. 操控全液压 3. 起升力大 4. 经济耐用",
        parameter: "",
      },
      {
        name: "厦工XG958K",
        type: "loader",
        typeName: "装载机",
        desc: "厦工XG958K装载机以高承载、高效、节能、易操控著称。",
        smallImg: "/images/products/engineer/loaders/厦工XG958K/图片1.jpg",
        images: "",
        features: "1. 承载力强 2. 工作效率高 3. 燃油经济 4. 操控灵活",
        parameter: "",
      },
      {
        name: "罐车",
        type: "truck",
        typeName: "罐车",
        desc: "外观整洁，内部清洁，适合运输各种液体货物。其密封性能良好，确保运输过程中的安全无泄漏。",
        smallImg: "/images/products/engineer/truck/1.jpg",
        images: "",
        features: "1. 外观整洁 2. 内部清洁 3. 密封性能好 4. 适合液体运输",
        parameter: "",
      },
      {
        name: "罐车",
        type: "truck",
        typeName: "罐车",
        desc: "油罐车专为安全高效运输液体燃料设计。",
        smallImg: "/images/products/engineer/truck/4.jpg",
        images: "",
        features: "1. 安全运输 2. 高效装卸 3. 防爆设计 4. 易于维护",
        parameter: "",
      },
      {
        name: "精品二手 01",
        type: "usedcar",
        typeName: "二手车",
        desc: "这款二手履带式挖掘机外观保养良好，性能稳定，适合中小型土方工程。其耐用的履带设计保证了在各种地形上的稳定作业",
        smallImg: "/images/products/engineer/usedcar/01/usedcar11.jpg",
        images: "",
        features: "1. 外观保养佳 2. 性能稳定 3. 履带耐用 4. 适合中小型工程",
        parameter: "",
      },
      {
        name: " 精品二手 02",
        type: "usedcar",
        typeName: "二手车",
        desc: "此款二手履带式挖掘机成色较新，操作简便，动力强劲，适合进行重型挖掘作业。其高效的液压系统提供了出色的挖掘力。",
        smallImg: "/images/products/engineer/usedcar/02/usedcar21.jpg",
        images: "",
        features: "1. 成色较新 2. 操作简便 3. 动力强劲 4. 高效液压系统",
        parameter: "",
      },
      {
        name: " 精品二手 03",
        type: "usedcar",
        typeName: "二手车",
        desc: "这款二手履带式挖掘机经过专业维护，性能可靠，具备良好的燃油经济性，适合长时间连续作业。其坚固的结构设计保证了耐用性。",
        smallImg: "/images/products/engineer/usedcar/03/usedcar31.jpg",
        images: "",
        features: "1. 专业维护 2. 性能可靠 3. 燃油经济 4. 结构坚固",
        parameter: "",
      },
      {
        name: " 精品二手 04",
        type: "usedcar",
        typeName: "二手车",
        desc: "这款二手履带式挖掘机虽然外观略显磨损，但内部机械状况良好，性价比高，适合预算有限但需要可靠挖掘力的用户。",
        smallImg: "/images/products/engineer/usedcar/04/usedcar41.jpg",
        images: "",
        features: "1. 性价比高 2. 内部状况良好 3. 适合预算有限 4. 可靠挖掘力",
        parameter: "",
      },
      {
        name: "小松PC200-11M0",
        type: "excavator",
        typeName: "挖掘机",
        desc: "小松PC200-11M0挖掘机以其卓越的性能、可靠性、燃油经济性和智能化控制系统在挖掘作业中表现出色。",
        smallImg:
          "/images/products/engineer/excavators/小松PC200-11M0/图片1.jpg",
        images: "",
        features: "1. 性能出色 2. 动力强劲 3. 操作灵活 4. 人性化设计",
        parameter: "",
      },
      {
        name: "SANY 215C",
        type: "excavator",
        typeName: "挖掘机",
        desc: "SY215C挖掘机凭借其强大的动力、精准操控、高效工作能力、舒适操作环境、高度可靠性、环保节能和维护方便性，成为理想的工程设备。",
        smallImg: "/images/products/engineer/excavators/SANY 215C/图片1.jpg",
        images: "",
        features: "1. 动力强劲 2. 操控精准 3. 高效作业 4. 舒适驾驶室",
        parameter: "",
      },
      {
        name: "SANY 215H",
        type: "excavator",
        typeName: "挖掘机",
        desc: "三一重工SY215H挖掘机以其卓越的动力、高效作业、燃油经济性、简便操作、舒适性、高可靠性和维修便捷性，满足多样化工程需求。",
        smallImg: "/images/products/engineer/excavators/SANY 215H/图片1.jpg",
        images: "",
        features: "1. 动力强劲 2. 作业高效 3. 燃油经济 4. 操作简便",
        parameter: "",
      },
      {
        name: "SANY 335H",
        type: "excavator",
        typeName: "挖掘机",
        desc: "三一重工SY335H挖掘机以其卓越的挖掘力、高效智能作业、舒适驾驶体验、稳定性和易维护性成为工程机械设备的理想选择。",
        smallImg: "/images/products/engineer/excavators/SANY 335H/图片1.jpg",
        images: "",
        features: "1. 挖掘能力强 2. 作业效率高 3. 驾驶室舒适 4. 维护便捷",
        parameter: "",
      },
    ],
  },
  {
    type: "agricultural",
    title: "农业机械",
    products: [
      {
        name: "AF88",
        type: "tractor",
        typeName: "收割机",
        desc: "AF88履带式联合收割机是高效、高配置、高品质的纵轴流收割机型，适合全喂入水稻收割。",
        smallImg: "/images/products/agricultural/水稻收割机/AF88.jpg",
        images: "",
        features: "1. 高效收割 2. 高端配置 3. 纵轴流设计 4. 适合水稻",
        parameter: "",
      },
      {
        name: "RG108",
        type: "tractor",
        typeName: "收割机",
        desc: "RG108PLUS履带式联合收割机专为高产量水稻设计，底盘升级，确保高效率收割。",
        smallImg: "/images/products/agricultural/水稻收割机/RG108.jpg",
        images: "",
        features: "1. 高产量设计 2. 底盘升级 3. 收获效率高 4. 适合水稻",
        parameter: "",
      },
      {
        name: "瑞得RD900",
        type: "truck",
        typeName: "拖拉机",
        desc: "瑞得RD900拖拉机配备东方红发动机，具有大扭矩、低油耗、高可靠性，适合牵引和驱动作业，结构紧凑，操作灵活。",
        smallImg: "/images/products/agricultural/拖拉机/900.jpg",
        images: "",
        features: "1. 东方红发动机 2. 动力强劲 3. 结构紧凑 4. 操作灵活",
        parameter: "",
      },
      {
        name: "瑞得RD904",
        type: "truck",
        typeName: "拖拉机",
        desc: "瑞得RD904拖拉机，东方红发动机，动力强劲，油耗低，结构紧凑，操作灵活。",
        smallImg: "/images/products/agricultural/拖拉机/904.jpg",
        images: "",
        features: "1. 扭矩大动力强 2. 高可靠性 3. 结构紧凑 4. 液压转向",
        parameter: "",
      },
      {
        name: "瑞得RD1000",
        type: "truck",
        typeName: "拖拉机",
        desc: "瑞得RD1000轮式拖拉机，搭载东方红发动机，提供强大动力，结构紧凑，操作灵活。",
        smallImg: "/images/products/agricultural/拖拉机/1000.jpg",
        images: "",
        features: "1. 扭矩大动力强 2. 低油耗高可靠性 3. 结构紧凑 4. 液压转向",
        parameter: "",
      },
    ],
  },
];
